# Generated by Django 5.2.4 on 2025-08-19 07:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='history',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Club history and information'),
        ),
        migrations.AlterField(
            model_name='management',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Biography and information'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='News article content'),
        ),
    ]
