# Generated by Django 5.2.4 on 2025-07-30 15:45

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubinfo',
            options={'verbose_name': 'Informace o klubu', 'verbose_name_plural': 'Informace o klubu'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Liga', 'verbose_name_plural': 'Ligy'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Novinka', 'verbose_name_plural': 'Novinky'},
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktní email'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kontaktní telefon'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='founded_year',
            field=models.IntegerField(default=1952, verbose_name='Rok založení'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='history',
            field=models.TextField(blank=True, verbose_name='Historie'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='name',
            field=models.CharField(default='TJ Družba Hlavnice', max_length=100, verbose_name='Název klubu'),
        ),
        migrations.AlterField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název ligy'),
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.CharField(max_length=20, verbose_name='Sezóna'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Zvýrazněno'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publikováno'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulek'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizováno'),
        ),
    ]
