# Generated by Django 5.2.4 on 2025-08-19 07:49

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_clubinfo_history_alter_management_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubinfo',
            options={'verbose_name': 'Informace o klubu', 'verbose_name_plural': 'Informace o klubu'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Událost', 'verbose_name_plural': 'Události'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Galerie', 'verbose_name_plural': 'Galerie'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Soutěž', 'verbose_name_plural': 'Soutěže'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Konfigurace hlavní stránky', 'verbose_name_plural': 'Konfigurace hlavní stránky'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['order', 'role'], 'verbose_name': 'Vedení klubu', 'verbose_name_plural': 'Vedení klubu'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date'], 'verbose_name': 'Zápas', 'verbose_name_plural': 'Zápasy'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aktualita', 'verbose_name_plural': 'Aktuality'},
        ),
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Návštěva stránky', 'verbose_name_plural': 'Návštěvy stránek'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['jersey_number'], 'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['position'], 'verbose_name': 'Tabulka', 'verbose_name_plural': 'Tabulky'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktní email'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kontaktní telefon'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='founded_year',
            field=models.IntegerField(default=1952, verbose_name='Rok založení'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='history',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Historie a informace o klubu', verbose_name='Historie klubu'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='name',
            field=models.CharField(default='TJ Družba Hlavnice', max_length=100, verbose_name='Název klubu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Datum a čas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_match',
            field=models.BooleanField(default=False, verbose_name='Je to zápas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Místo konání'),
        ),
        migrations.AlterField(
            model_name='event',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.match', verbose_name='Zápas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název události'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.event', verbose_name='Událost'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Nahráno'),
        ),
        migrations.AlterField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název soutěže'),
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.CharField(max_length=20, verbose_name='Sezóna'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='featured_news',
            field=models.ManyToManyField(blank=True, limit_choices_to={'published': True}, to='football.news', verbose_name='Doporučené aktuality'),
        ),
        migrations.AlterField(
            model_name='management',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Biografie a informace', verbose_name='Biografie'),
        ),
        migrations.AlterField(
            model_name='management',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='management',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Křestní jméno'),
        ),
        migrations.AlterField(
            model_name='management',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='management',
            name='order',
            field=models.IntegerField(default=0, help_text='Pořadí zobrazení', verbose_name='Pořadí'),
        ),
        migrations.AlterField(
            model_name='management',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='management',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='management/', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='management',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'Předseda'), ('COACH', 'Trenér'), ('ASSISTANT', 'Asistent trenéra'), ('TREASURER', 'Pokladník'), ('SECRETARY', 'Sekretář'), ('MANAGER', 'Manažer'), ('OTHER', 'Ostatní')], max_length=20, verbose_name='Funkce'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skóre hostů'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football.team', verbose_name='Hostující tým'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(verbose_name='Datum a čas'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skóre domácích'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football.team', verbose_name='Domácí tým'),
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.league', verbose_name='Soutěž'),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Místo konání'),
        ),
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Poznámky'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rozhodčí'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Obsah článku', verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Doporučený článek'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publikováno'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nadpis'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Upraveno'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP adresa'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='page_name',
            field=models.CharField(max_length=100, verbose_name='Název stránky'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Čas návštěvy'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Křestní jméno'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Góly'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(verbose_name='Číslo dresu'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DEF', 'Obránce'), ('MID', 'Záložník'), ('FWD', 'Útočník')], max_length=3, verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Červené karty'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.team', verbose_name='Tým'),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Žluté karty'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='drawn',
            field=models.IntegerField(default=0, verbose_name='Remízy'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_against',
            field=models.IntegerField(default=0, verbose_name='Góly obdržené'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='goals_for',
            field=models.IntegerField(default=0, verbose_name='Góly vstřelené'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.league', verbose_name='Soutěž'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='lost',
            field=models.IntegerField(default=0, verbose_name='Prohry'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='played',
            field=models.IntegerField(default=0, verbose_name='Odehráno'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='position',
            field=models.IntegerField(verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team', verbose_name='Tým'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='won',
            field=models.IntegerField(default=0, verbose_name='Výhry'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Vlajka/Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok založení'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_club_team',
            field=models.BooleanField(default=False, help_text='Označte, pokud je to tým TJ Hlavnice', verbose_name='Náš tým'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.league', verbose_name='Soutěž'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název týmu'),
        ),
    ]
