# Generated by Django 5.2.4 on 2025-07-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_clubinfo_options_alter_league_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['jersey_number'], 'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Góly'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(verbose_name='Číslo dresu'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Brankář'), ('DEF', 'Obránce'), ('MID', 'Záložník'), ('FWD', 'Útočník')], max_length=3, verbose_name='Pozice'),
        ),
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Červené karty'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.team', verbose_name='Tým'),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Žluté karty'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Vlajka'),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok založení'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_club_team',
            field=models.BooleanField(default=False, help_text='Označte, pokud se jedná o tým TJ Hlavnice', verbose_name='Náš tým'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název týmu'),
        ),
    ]
