# Generated by Django 5.2.4 on 2025-07-30 17:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_player_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='history',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Historie'),
        ),
    ]
