# Generated by Django 5.2.5 on 2025-08-19 10:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_clubinfo_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='history',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Historie a informace o klubu', verbose_name='Historie klubu'),
        ),
        migrations.AlterField(
            model_name='management',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Biografie a informace', verbose_name='Biografie'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Obsah článku', verbose_name='Obsah'),
        ),
    ]
