# Generated by Django 5.2.4 on 2025-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_clubinfo_history_alter_management_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kolo'),
        ),
    ]
