# Generated by Django 5.2.4 on 2025-07-30 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_clubinfo_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='milestones',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Milníky'),
        ),
    ]
