# Generated by Django 5.2.5 on 2025-08-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_match_round_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název galerie')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Titulní obrázek')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.event', verbose_name='Událost')),
            ],
            options={
                'verbose_name': 'Galerie (album)',
                'verbose_name_plural': 'Galerie (alba)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='football.galleryalbum', verbose_name='Album'),
        ),
    ]
