# Generated by Django 5.2.5 on 2025-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_galleryalbum_gallery_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Zkrácený název'),
        ),
    ]
