# Generated by Django 5.2.4 on 2025-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_team_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kalendář TJ Družba Hlavnice', max_length=100, verbose_name='Název kalendáře')),
                ('calendar_id', models.CharField(blank=True, help_text='ID Google kalendáře (např. abcd1234@group.calendar.google.com)', max_length=255, verbose_name='ID Google kalendáře')),
                ('api_key', models.CharField(blank=True, help_text='API klíč pro přístup k Google Calendar API', max_length=255, verbose_name='Google API klíč')),
                ('is_active', models.BooleanField(default=False, help_text='Zapnout zobrazení kalendáře', verbose_name='Aktivní')),
                ('max_events', models.IntegerField(default=50, help_text='Maximální počet událostí k zobrazení', verbose_name='Maximum událostí')),
                ('show_past_events', models.BooleanField(default=True, verbose_name='Zobrazit minulé události')),
                ('past_events_days', models.IntegerField(default=30, help_text='Kolik dní zpět zobrazit minulé události', verbose_name='Dny zpět')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Nastavení Google kalendáře',
                'verbose_name_plural': 'Nastavení Google kalendáře',
            },
        ),
    ]
