# Generated by Django 5.2.4 on 2025-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_googlecalendarsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarsettings',
            name='max_events',
            field=models.IntegerField(default=50, help_text='Maximální počet událostí k zobrazení (nyní: 6 nadcházejících + 6 minulých)', verbose_name='Maximum událostí'),
        ),
        migrations.AlterField(
            model_name='googlecalendarsettings',
            name='past_events_days',
            field=models.IntegerField(default=30, help_text='Kolik dní zpět hledat minulé události (zobrazí se posledních 6)', verbose_name='Dny zpět'),
        ),
    ]
