# Generated by Django 5.2.4 on 2025-08-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_alter_googlecalendarsettings_max_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(help_text='Vyberte více obrázků najednou (Ctrl+Click nebo Cmd+Click)', upload_to='temp_uploads/', verbose_name='Obrázky')),
                ('default_title_prefix', models.CharField(default='Fotka', help_text="Každý obrázek bude pojmenován: 'Předpona + číslo'", max_length=100, verbose_name='Předpona názvu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.galleryalbum', verbose_name='Album')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.event', verbose_name='Událost')),
            ],
            options={
                'verbose_name': 'Hromadné nahrání fotek',
                'verbose_name_plural': 'Hromadné nahrání fotek',
            },
        ),
    ]
